site_name: Gitlab Advanced Workflow Template
site_description: Gitlab Advanced Workflow Template
repo_url: https://github.com/rhdhorchestrator/workflow-software-templates
docs_dir: docs

plugins:
  - techdocs-core

theme:
  name: material
  palette:
    primary: 'red'
    accent: 'grey'
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - navigation.sections
    - toc.integrate
    - toc.follow
    - content.code.copy

markdown_extensions:
  - admonition
  - toc:
      permalink: true

nav: 
  - Gitlab Advanced Workflow Template:
      - Gitlab Advanced Workflow Template: 'template.yaml'

